### ISSUE TITLE
One image

### ISSUE THREAD

**Issue by wyklif** [KevinWang15/ionic2-multi-image-upload#2]
Hi,  thanks for the great plugin,  however can i tweak this so that i can use it in instances where only one image is to be uploaded e.g profile pics so that it doesnt allow multiple also i am assuming i have to add all the providers in my app.module.ts?

**Comment by kodeine** [comment]
Replace the div in html
```html
<div class="image-wrapper add-image-btn" *ngIf="!isUploading && imagesValue.length < maxLimit"
....
```

And in TS 
```ts
protected imagesValue: Array<any> = [];
@Input() public maxLimit: number = 3;
```

**Comment by wyklif** [comment]
Thanks @kodeine,  though imagesValue is going to be undefined initially

**Comment by wyklif** [comment]
solved it by using the `public images: any = [];` array instead of imagesValue

**Comment by wyklif** [comment]
thanks again @kodeine
